//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRoute()
        {
            this.TUser = new HashSet<TUser>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public double length { get; set; }
        public string difficulty { get; set; }
        public bool wheelchairAccessible { get; set; }
        public bool approved { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<int> routeRating { get; set; }
        public Nullable<double> distanceFromUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TUser> TUser { get; set; }
    }
}
